correctexam/corrigeExamFront

src/main/webapp/app/scanexam/alignscan/alignscan.component.ts
src/main/webapp/app/scanexam/associer-copies-etudiants/associer-copies-etudiants.component.html
src/main/webapp/app/scanexam/associer-copies-etudiants/associer-copies-etudiants.component.ts
src/main/webapp/app/scanexam/corrigequestion/ZoneCorrectionHandler.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/import-student/import-student.component.html
src/main/webapp/app/scanexam/import-student/import-student.component.ts
src/main/webapp/app/scanexam/voircopie/ZoneVoirCopieHandler.ts
src/main/webapp/app/scanexam/voircopie/voircopie.component.ts
webpack/proxy.conf.js

Mainly on page resize and fabricjs

correct several typos raised by steven

---

src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.html
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts

fix(marking): clicking on unmarking a question does nothing

---

src/main/webapp/app/scanexam/statsexam/statsexam.component.html
src/main/webapp/app/scanexam/statsexam/statsexam.component.scss
src/main/webapp/app/scanexam/statsexam/statsexam.component.ts

Only the scale of the first one is taken into consideration.

[FIXING BUG] a question can now be split in several parts in the template

---

src/main/webapp/app/entities/exam/service/exam.service.ts
src/main/webapp/app/scanexam/alignscan/alignscan.component.ts
src/main/webapp/app/scanexam/associer-copies-etudiants/associer-copies-etudiants.component.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.html
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/exam-detail/exam-detail.component.ts
src/main/webapp/i18n/fr/scanexammodule.json

Do not create studentResponse when navigating but just when adding a first comment or a first grade

First try to update the status of your exam

---

package-lock.json
package.json
src/main/webapp/app/entities/scan/service/scan.service.ts
src/main/webapp/app/opencv.worker.ts
src/main/webapp/app/scanexam/alignscan/alignscan.component.ts
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/PageHandler.ts
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.ts
src/main/webapp/app/scanexam/associer-copies-etudiants/associer-copies-etudiants.component.ts
src/main/webapp/app/scanexam/chargerscan/chargerscan.component.ts
src/main/webapp/app/scanexam/exam-detail/cacheUpload.service.ts
src/main/webapp/app/scanexam/exam-detail/exam-detail.component.ts
webpack/webpack.custom.js

@arnobl if you want to review ;)

integrate esbuild for dev config and serve config

---

src/main/webapp/app/scanexam/statsexam/statsexam.component.html
src/main/webapp/app/scanexam/statsexam/statsexam.component.ts

Two bugs fixed that appears when questions are not ordered in the template:
- incorrect display of the questions
- incorrect computation of question data

Fix display errors in the stats panel

---

src/main/webapp/app/scanexam/statsexam/statsexam.component.html
src/main/webapp/app/scanexam/statsexam/statsexam.component.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

Currently the stats panel does not ignore ABI students so that they are included in the stats computations.

fix(stat): must ignore ABI students

---

src/main/webapp/app/config/font-awesome-icons.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.html
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/preference-page/preference.service.ts
src/main/webapp/app/scanexam/scanexam.module.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

first contribution to improve correct step layout

---

src/main/webapp/app/scanexam/annotate-template/annotate-template.component.ts
src/main/webapp/app/scanexam/annotate-template/paint/event-handler.service.ts
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.scss
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.ts
src/main/webapp/app/scanexam/annotate-template/paint/paint.component.html
src/main/webapp/app/scanexam/annotate-template/paint/questionpropertiesview/questionpropertiesview.component.html
src/main/webapp/app/scanexam/annotate-template/paint/questionpropertiesview/questionpropertiesview.component.ts
src/main/webapp/app/scanexam/exam-detail/cacheUpload.service.ts
src/main/webapp/app/scanexam/exam-detail/exam-detail.component.ts
src/main/webapp/app/scanexam/scanexam.module.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

https://docs.google.com/document/d/1GiW906xbyQwC3L7yS7BDHBDM7uLeygv706tgCOZhcQk/edit?usp=sharing

improvement based on Juliette Arnaud Comments

---

src/main/webapp/app/scanexam/statsexam/statsexam.component.ts

update small bug when ordering a note for specific question

---

src/main/webapp/app/scanexam/annotate-template/paint/event-handler.service.ts
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.html
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.ts

More work on reducing the route traffic while dealing the template annotations

fix(annotate): reducing the route queries

---

src/main/webapp/app/scanexam/annotate-template/paint/event-handler.service.ts
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.html
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.ts

Reverts correctexam/corrigeExamFront#265
Create lots of bug when deleting a previous question and recreate a new one

Revert "fix(annotate): reducing the route queries"

---

package-lock.json
package.json
src/main/webapp/app/app.constants.ts
src/main/webapp/app/core/auth/account.service.ts
src/main/webapp/app/core/auth/auth-jwt.service.ts
src/main/webapp/app/environment/environment.prod.ts
src/main/webapp/app/environment/environment.ts
src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.spec.ts
src/main/webapp/app/home/home.component.ts
src/main/webapp/app/layouts/navbar/navbar.component.html
src/main/webapp/app/layouts/navbar/navbar.component.ts
src/main/webapp/app/login/login.service.ts
webpack/environment.js
webpack/proxy.conf.js
webpack/webpack.config.js
webpack/webpack.custom.js

merge Barbapapou server auth cas test

Barbapapou server auth cas test

---

src/main/webapp/app/scanexam/statsexam/statsexam.component.ts

Concerns the stats panel. Sorting by last/first names did not work.
Also try to sort INEs as number when possible.

fix(stats): incorrect sorting by names

---

src/main/webapp/app/align.pool.worker.ts
src/main/webapp/app/scanexam/alignscan/alignscan.component.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.html
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/marking-summary/marking-summary.component.html
src/main/webapp/app/scanexam/marking-summary/marking-summary.component.ts
src/main/webapp/app/scanexam/statsexam/statsexam.component.html
src/main/webapp/app/scanexam/statsexam/statsexam.component.ts
src/main/webapp/app/scanexam/voircopie/voircopie.component.html
src/main/webapp/app/scanexam/voircopie/voircopie.component.ts
src/main/webapp/app/scanexam/voirreponse/voirreponse.component.html
src/main/webapp/app/scanexam/voirreponse/voirreponse.component.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

294 support the fact that questions does not start from 1

---

src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.html
src/main/webapp/app/scanexam/annotate-template/paint/fabric-canvas/fabric-canvas.component.ts

Not sure it is the good fix.
With the change of zoom from 100% to page-width, the annotation auto created from PDF metadata are not of the good size.

fix(anot): automated annotations not correctly positioned

---

src/main/webapp/app/scanexam/import-student/import-student.component.html
src/main/webapp/app/scanexam/import-student/import-student.component.ts

Provide index when showing students' list

close #290

---

package-lock.json
package.json
src/main/webapp/app/config/font-awesome-icons.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.html
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/corrigequestion/keyboardshortcut/keyboardshortcut.component.html
src/main/webapp/app/scanexam/corrigequestion/keyboardshortcut/keyboardshortcut.component.spec.ts
src/main/webapp/app/scanexam/corrigequestion/keyboardshortcut/keyboardshortcut.component.ts
src/main/webapp/app/scanexam/preference-page/keyboardshortcut.service.ts
src/main/webapp/app/scanexam/scanexam.module.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

a first attempt to let use define its own keyboard shortcut bound to comments

close #222

---

src/main/webapp/app/config/font-awesome-icons.ts
src/main/webapp/app/opencv.worker.ts
src/main/webapp/app/scanexam/associer-copies-etudiants/associer-copies-etudiants.component.ts
src/main/webapp/app/scanexam/comparestudentanswer/comparestudentanswer.component.html
src/main/webapp/app/scanexam/comparestudentanswer/comparestudentanswer.component.ts
src/main/webapp/app/scanexam/corrigequestion/corrigequestion.component.ts
src/main/webapp/app/scanexam/marking-summary/marking-summary.component.ts
src/main/webapp/app/scanexam/preference-page/preference.service.ts
src/main/webapp/app/scanexam/scanexam.module.ts
src/main/webapp/app/scanexam/services/align-images.service.ts
src/main/webapp/app/scanexam/voircopie/voircopie.component.ts
src/main/webapp/app/scanexam/voirreponse/voirreponse.component.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

First attempt to group student response for batch correction

305 group answers for batch correction

---

src/main/webapp/app/scanexam/voircopie/voircopie.component.html
src/main/webapp/app/scanexam/voircopie/voircopie.component.ts
src/main/webapp/i18n/en/scanexammodule.json
src/main/webapp/i18n/fr/scanexammodule.json

402 feedback view add a link to the correction view for instructors feature request
